# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.provider "hyperv" do |v|
    v.memory = 4096
    v.cpus = 8
  end
  config.vm.box = "gusztavvargadr/windows-10"
  config.vm.box_version = "2506.0.0"
  config.vm.boot_timeout = 1200
end
